# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGridLayout, QGroupBox,
    QLabel, QPlainTextEdit, QProgressBar, QPushButton,
    QRadioButton, QScrollArea, QSizePolicy, QSlider,
    QStackedWidget, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.setWindowModality(Qt.ApplicationModal)
        Widget.resize(911, 601)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(160, 164, 227, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(207, 209, 241, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(80, 82, 113, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(107, 109, 151, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 127))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(80, 82, 113, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        Widget.setPalette(palette)
        icon = QIcon()
        iconThemeName = u"applications-development"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u"images/ammperbitlogo.ico", QSize(), QIcon.Normal, QIcon.Off)

        Widget.setWindowIcon(icon)
        Widget.setAutoFillBackground(True)
        self.stackedWidget = QStackedWidget(Widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 891, 581))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.stackedWidget.setPalette(palette1)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.pushButton = QPushButton(self.page)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(200, 360, 201, 61))
        font = QFont()
        font.setFamilies([u"Franklin Gothic Medium"])
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton_2 = QPushButton(self.page)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(480, 360, 201, 61))
        self.pushButton_2.setFont(font)
        self.pushButton_3 = QPushButton(self.page)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(370, 480, 141, 51))
        font1 = QFont()
        font1.setFamilies([u"Franklin Gothic Book"])
        font1.setPointSize(11)
        font1.setItalic(True)
        self.pushButton_3.setFont(font1)
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(200, 430, 211, 16))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        self.label_6.setPalette(palette2)
        font2 = QFont()
        font2.setFamilies([u"Franklin Gothic Book"])
        font2.setPointSize(8)
        self.label_6.setFont(font2)
        self.label_8 = QLabel(self.page)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(210, 0, 471, 351))
        self.label_8.setMinimumSize(QSize(451, 221))
        self.label_8.setMaximumSize(QSize(16777, 16777))
        self.label_8.setPixmap(QPixmap(u"images/AMMPER_Logo1.PNG"))
        self.label_8.setScaledContents(True)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.pushButton_4 = QPushButton(self.page_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(360, 530, 161, 31))
        self.pushButton_4.setFont(font)
        self.groupBox_2 = QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 260, 871, 101))
        self.groupBox_2.setFont(font)
        self.horizontalSlider = QSlider(self.groupBox_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(20, 40, 821, 31))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(6)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 70, 16, 16))
        font3 = QFont()
        font3.setFamilies([u"Franklin Gothic Book"])
        font3.setPointSize(9)
        self.label_20.setFont(font3)
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(180, 70, 21, 16))
        self.label_21.setFont(font3)
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(350, 70, 16, 16))
        self.label_22.setFont(font3)
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(500, 70, 21, 16))
        self.label_23.setFont(font3)
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(670, 70, 21, 16))
        self.label_24.setFont(font3)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(820, 70, 21, 16))
        self.label_25.setFont(font3)
        self.groupBox_3 = QGroupBox(self.page_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 380, 411, 71))
        self.groupBox_3.setFont(font)
        self.radioButton_5 = QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(30, 30, 89, 20))
        font4 = QFont()
        font4.setFamilies([u"Franklin Gothic Book"])
        font4.setPointSize(10)
        self.radioButton_5.setFont(font4)
        self.radioButton_6 = QRadioButton(self.groupBox_3)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(270, 30, 89, 20))
        self.radioButton_6.setFont(font4)
        self.groupBox_4 = QGroupBox(self.page_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(440, 380, 441, 71))
        self.groupBox_4.setFont(font)
        self.radioButton_7 = QRadioButton(self.groupBox_4)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(40, 30, 89, 20))
        self.radioButton_7.setFont(font4)
        self.radioButton_8 = QRadioButton(self.groupBox_4)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.radioButton_8.setGeometry(QRect(260, 30, 89, 20))
        self.radioButton_8.setFont(font4)
        self.groupBox_5 = QGroupBox(self.page_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 460, 871, 51))
        self.groupBox_5.setFont(font)
        self.checkBox = QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(60, 20, 161, 20))
        self.checkBox.setFont(font2)
        self.plainTextEdit = QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(230, 20, 191, 21))
        palette3 = QPalette()
        brush9 = QBrush(QColor(229, 220, 255, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        self.plainTextEdit.setPalette(palette3)
        self.plainTextEdit.setFont(font4)
        self.checkBox_2 = QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(610, 20, 171, 20))
        self.checkBox_2.setFont(font2)
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(440, 20, 81, 16))
        font5 = QFont()
        font5.setFamilies([u"Franklin Gothic Book"])
        font5.setPointSize(8)
        font5.setItalic(True)
        self.label_7.setFont(font5)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, -10, 441, 191))
        self.label_9.setPixmap(QPixmap(u"images/AMMPER_Clear1.PNG"))
        self.label_9.setScaledContents(True)
        self.groupBox = QGroupBox(self.page_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 180, 871, 71))
        self.groupBox.setFont(font)
        self.radioButton = QRadioButton(self.groupBox)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(20, 30, 161, 20))
        self.radioButton.setFont(font4)
        self.radioButton_2 = QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(240, 30, 121, 20))
        self.radioButton_2.setFont(font4)
        self.radioButton_3 = QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(500, 30, 131, 20))
        self.radioButton_3.setFont(font4)
        self.radioButton_4 = QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(740, 30, 89, 20))
        self.radioButton_4.setFont(font4)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.progressBar = QProgressBar(self.page_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(220, 370, 441, 22))
        font6 = QFont()
        font6.setFamilies([u"Franklin Gothic Book"])
        self.progressBar.setFont(font6)
        self.progressBar.setValue(24)
        self.label_2 = QLabel(self.page_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(380, 430, 97, 18))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 490, 74, 16))
        self.label_3.setFont(font6)
        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(220, 40, 441, 321))
        self.label_10.setPixmap(QPixmap(u"images/AMMPER_Logo1.PNG"))
        self.label_10.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.pushButton_5 = QPushButton(self.page_4)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(340, 490, 211, 51))
        self.pushButton_5.setFont(font)
        self.layoutWidget = QWidget(self.page_4)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 30, 861, 441))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.layoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.label_12 = QLabel(self.layoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)

        self.label_19 = QLabel(self.layoutWidget)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout.addWidget(self.label_19, 0, 2, 1, 1)

        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_14 = QLabel(self.page_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(650, 120, 271, 231))
        self.label_14.setPixmap(QPixmap(u"images/NASA_logo.svg.webp"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.page_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(640, 330, 271, 271))
        self.label_15.setPixmap(QPixmap(u"images/nasa_slstp_logo.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.page_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 260, 231, 211))
        self.label_16.setPixmap(QPixmap(u"images/BCMLogo.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.page_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 480, 231, 91))
        self.label_17.setPixmap(QPixmap(u"images/psgc.jpg"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.page_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(230, -30, 481, 351))
        self.label_18.setPixmap(QPixmap(u"images/AMMPER_Logo1.PNG"))
        self.label_18.setScaledContents(True)
        self.scrollArea = QScrollArea(self.page_5)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(270, 290, 391, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 389, 279))
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_5)
        self.label_18.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.scrollArea.raise_()

        self.retranslateUi(Widget)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"AMMPER v2.0", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"Launch GUI", None))
        self.pushButton_2.setText(QCoreApplication.translate("Widget", u"Launch CLI", None))
        self.pushButton_3.setText(QCoreApplication.translate("Widget", u"Credits", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"*** Recommended for first time users.", None))
        self.label_8.setText("")
        self.pushButton_4.setText(QCoreApplication.translate("Widget", u"Launch", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Widget", u"Radiation Dose (150 MeV Proton Only)", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"0", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"2.5", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"5", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"10", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"20", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"30", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Widget", u"Cell Type", None))
        self.radioButton_5.setText(QCoreApplication.translate("Widget", u"Wild Type", None))
        self.radioButton_6.setText(QCoreApplication.translate("Widget", u"rad51", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Widget", u"ROS Model", None))
        self.radioButton_7.setText(QCoreApplication.translate("Widget", u"Basic", None))
        self.radioButton_8.setText(QCoreApplication.translate("Widget", u"Complex", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Widget", u"Results", None))
        self.checkBox.setText(QCoreApplication.translate("Widget", u"Export data to (type path):", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("Widget", u"/Results", None))
        self.checkBox_2.setText(QCoreApplication.translate("Widget", u"Display onscreen", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Valid path.", None))
        self.label_9.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"Simulation Type", None))
        self.radioButton.setText(QCoreApplication.translate("Widget", u"150MeV Proton", None))
        self.radioButton_2.setText(QCoreApplication.translate("Widget", u"NSRL GCRSim", None))
        self.radioButton_3.setText(QCoreApplication.translate("Widget", u"Deep Space", None))
        self.radioButton_4.setText(QCoreApplication.translate("Widget", u"Gamma", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Generation 10", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Did you know: ", None))
        self.label_10.setText("")
        self.pushButton_5.setText(QCoreApplication.translate("Widget", u"Exit", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"TextLabel", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
    # retranslateUi

